sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t deepak2705/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deepak2705/docker-react npm run test -- --coverage
